(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const money=value=>'NT$ '+Number(value||0).toLocaleString();
const text=(id,value)=>$(id).textContent=value||'—';
const row=(label,value)=>`<div class="detail-row"><span>${esc(label)}</span><b>${esc(value||'—')}</b></div>`;
const fullAddress=data=>[data?.postalCode,data?.city,data?.district,data?.address].filter(Boolean).join(' ');
function readOrders(key){try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
function invoiceName(type){return({member_address:'會員載具（寄到訂購地址）',cloud_mobile:'雲端發票－手機條碼',company:'公司電子發票',donate:'捐贈發票',personal:'個人電子發票'}[type]||type||'個人電子發票')}
function renderItems(order,goods){const items=order.items||[];$('orderItems').innerHTML=items.map(item=>{const quantity=Number(goods?item.quantity:item.guests)||0,meta=goods?`${item.unit||'商品'}・${quantity} 件`:`${item.date||'日期未提供'}・${quantity} 人`,image=item.img||item.image||'../imgs/水蜜桃.png';return `<article class="order-detail-item"><img src="${esc(image)}" alt="${esc(item.name||item.title||'訂單品項')}" onerror="this.onerror=null;this.src='../imgs/水蜜桃.png'"><div><h3>${esc(item.name||item.title||'訂單品項')}</h3><p>${esc(meta)}<br>單價 ${money(item.price)}</p></div><strong>${money(Number(item.price)*quantity)}</strong></article>`}).join('')||'<p class="order-note-detail">此訂單沒有品項資料。</p>';return items}
function renderProgress(goods){const labels=goods?['訂單成立','付款完成','備貨配送']:['訂單成立','付款完成','預約完成'];$('progress').innerHTML=labels.map(label=>`<div class="progress-step"><i></i>${label}</div>`).join('')}
function render(){const params=new URLSearchParams(location.search),id=params.get('id')||'',requested=params.get('type')||'',email=(localStorage.getItem('sbir_current_user')||'demo@example.com').toLowerCase();let type=requested;if(!type)type=id.startsWith('GD')?'goods':'experience';const source=type==='goods'?readOrders('goodsOrders'):readOrders('experienceOrders');const order=source.find(item=>item.id===id&&String(item.userEmail||'').toLowerCase()===email);if(!order){$('detailView').classList.add('hidden');$('notFound').classList.add('show');return}const goods=type==='goods',created=new Date(order.createdAt),date=Number.isNaN(created.getTime())?'—':new Intl.DateTimeFormat('zh-TW',{dateStyle:'long',timeStyle:'short'}).format(created);document.title=`${order.id}｜詳細訂單｜桃園偏鄉輕旅行`;text('orderKind',goods?'LOCAL GOODS ORDER':'EXPERIENCE ORDER');text('orderId','訂單編號：'+order.id);text('orderStatus',order.status||'已付款');text('itemKindEnglish',goods?'LOCAL GOODS':'EXPERIENCE COURSE');text('itemKind',goods?'在地好物':'體驗課程');renderProgress(goods);const items=renderItems(order,goods);let computedSubtotal=items.reduce((sum,item)=>sum+Number(item.price||0)*Number(goods?item.quantity:item.guests||0),0);
if(goods){const buyer=order.buyer||{},recipient=order.recipient||{},delivery=order.delivery||{};$('contactTitle').textContent='訂購人資訊';$('contactDetails').innerHTML=row('姓名',buyer.name)+row('手機號碼',buyer.phone)+row('電子信箱',buyer.email)+row('訂購人地址',fullAddress(buyer));const deliveryName=delivery.method==='store'?'超商取貨':'宅配到府',deliveryValue=delivery.method==='store'?[delivery.storeChain,delivery.storeName,delivery.storeId&&`店號 ${delivery.storeId}`,delivery.storeAddress].filter(Boolean).join('｜'):fullAddress(delivery);$('recipientDetails').innerHTML=row('收件人姓名',recipient.name)+row('收件人手機',recipient.phone)+row('收件人信箱',recipient.email)+row('收件人地址',fullAddress(recipient))+row('配送方式',deliveryName)+row('配送／取貨資訊',deliveryValue);const invoice=order.invoice||{};$('invoiceDetails').innerHTML=row('發票類型',invoiceName(invoice.type))+row('發票通知信箱',invoice.email)+row('手機條碼',invoice.carrierNumber)+row('統一編號',invoice.taxId)+row('公司名稱',invoice.companyName);text('orderNote',order.orderNote||'無特別備註');$('summaryDetails').innerHTML=row('建立時間',date)+row('付款方式',order.payment||'線上付款')+row('商品項數',items.length+' 項')+row('商品總件數',items.reduce((sum,item)=>sum+Number(item.quantity||0),0)+' 件')+row('折價券／折扣碼',order.coupon?.title||order.coupon?.code||'未使用');text('subtotal',money(order.subtotal??computedSubtotal));text('shipping',Number(order.shipping||0)?money(order.shipping):'免運');text('discount',Number(order.discount||0)?'− '+money(order.discount):money(0));$('continueLink').href='在地好物直送.html';$('continueLink').textContent='繼續選購在地好物'}else{const contact=order.contact||{};$('contactTitle').textContent='報名聯絡資料';$('contactDetails').innerHTML=row('姓名',[contact.lastName,contact.firstName].filter(Boolean).join(' '))+row('國家／地區',contact.country)+row('手機號碼',[contact.phoneRegion,contact.phone].filter(Boolean).join(' '))+row('電子信箱',contact.email);$('recipientSection').classList.add('hidden');$('noteSection').classList.add('hidden');$('invoiceStep').textContent='03';const invoice=order.invoice||{},carrier=invoice.carrierType==='mobile'?'手機條碼':invoice.carrierType;$('invoiceDetails').innerHTML=row('發票類型',invoiceName(invoice.type))+row('寄送電子郵件',invoice.email)+row('載具類型',carrier)+row('載具號碼',invoice.carrierNumber);$('summaryDetails').innerHTML=row('建立時間',date)+row('付款方式','線上付款')+row('課程項數',items.length+' 項')+row('參加人次',items.reduce((sum,item)=>sum+Number(item.guests||0),0)+' 人')+row('預約狀態',order.status||'已付款');text('subtotal',money(computedSubtotal));$('shippingRow').classList.add('hidden');$('discountRow').classList.add('hidden');$('continueLink').href='體驗活動線上報名.html';$('continueLink').textContent='繼續探索體驗課程'}text('total',money(order.total));}
document.addEventListener('DOMContentLoaded',render);
})();