const fieldItems=[
{id:1,name:"拉拉山巨木群步道",district:"桃園市復興區",category:"山林秘境",tags:["步道","避暑","巨木"],image:"assets/fields/01.jpg?v=20260819-14",stay:"2–3 小時",pace:"森林健行",season:"四季皆宜",address:"桃園市復興區華陵里",hours:"依園區公告，建議白天到訪",ticket:"部分區域須依現場規定",reminder:"山區易起霧，請備妥雨具",lead:"走進雲霧與檜木交織的山徑，在緩慢的步伐裡感受拉拉山最沉靜的一面。",body:"<h2>與千年巨木相遇</h2><p>步道沿著山勢穿梭於紅檜、扁柏與闊葉林間，空氣裡帶著樹脂與濕潤苔蘚的氣味。不同路段可依體力彈性安排，適合喜歡森林散步與自然觀察的旅人。</p><h2>旅行建議</h2><p>清晨光線柔和、人潮較少，也較容易看見山嵐。山區路面可能濕滑，建議穿著抓地力良好的鞋，並預留回程車程。</p>"},
{id:2,name:"大溪老茶廠",district:"桃園市大溪區",category:"客庄文化",tags:["茶文化","歷史建築","室內"],image:"assets/fields/02.jpg?v=20260819-14",stay:"1–2 小時",pace:"慢遊品茶",season:"四季皆宜",address:"桃園市大溪區新峰里",hours:"09:30–17:00，休館日依公告",ticket:"入館方式依現場公告",reminder:"團體導覽建議事先預約",lead:"在老建築的木窗與茶香之間，讀一段大溪製茶產業與地方生活的故事。",body:"<h2>老建築裡的茶時光</h2><p>廠房保留製茶空間的尺度與細節，從通風窗、木構到機具配置，都能看見過去產業因應氣候與工序的智慧。</p><h2>慢慢看，也慢慢喝</h2><p>參觀後可安排一段品茶時間，從香氣與滋味認識茶葉，也讓旅程在安靜的室內節奏裡稍作停留。</p>"},
{id:3,name:"三坑老街與自然生態公園",district:"桃園市龍潭區",category:"老街聚落",tags:["美食","單車","客庄"],image:"assets/fields/03.jpg?v=20260819-14",stay:"2–3 小時",pace:"聚落散步",season:"秋冬舒適",address:"桃園市龍潭區三坑里",hours:"戶外空間全天開放",ticket:"自由參觀",reminder:"店家營業時間各異",lead:"從短短一條老街走到水圳與埤塘，感受客庄聚落和自然地景緊密相連的日常。",body:"<h2>老街不只是街屋</h2><p>沿途可看見信仰、飲食與生活產業留下的痕跡。走出聚落後，景色逐漸轉為田野與水岸，適合以步行或單車串連。</p><h2>半日散步提案</h2><p>建議先在老街用餐，再前往自然生態公園散步；傍晚光線較柔和，也適合拍攝田野與水岸。</p>"},
{id:4,name:"宇內溪戲水區",district:"桃園市復興區",category:"山林秘境",tags:["親水","親子","瀑布"],image:"assets/fields/04.jpg?v=20260819-14",stay:"2–4 小時",pace:"親水探索",season:"夏季限定",address:"桃園市復興區義盛里",hours:"開放狀況依季節與天候公告",ticket:"依現場管理規定",reminder:"豪雨或水勢不穩時勿進入",lead:"清涼溪水穿過山谷，適合在安全開放期間安排一趟親近自然的夏日行程。",body:"<h2>在溪谷裡感受盛夏</h2><p>溪流與岩石構成多層次的親水空間，旅人可在開放區域停留、觀察溪谷生態。所有活動應以現場警示與管理人員指示為準。</p><div class='article-note'>請留意午後雷陣雨與上游水勢；孩童須由成人全程陪同，並穿著合適的防滑裝備。</div>"},
{id:5,name:"觀音永安漁港海螺館",district:"桃園市新屋區",category:"海岸漁村",tags:["海景","建築美學","夕陽"],image:"assets/fields/01.jpg?v=20260819-14",stay:"1–2 小時",pace:"海岸漫遊",season:"春秋最佳",address:"桃園市新屋區永安漁港周邊",hours:"戶外全天，館舍依公告",ticket:"自由參觀",reminder:"海邊風大，注意保暖",lead:"以海螺意象的建築作為旅程地標，串連漁港、海風與夕陽，是海岸線上輕鬆的一站。",body:"<h2>沿著海風走</h2><p>建築曲線回應海洋意象，周邊可順遊漁港與觀景空間。黃昏前抵達，能保留時間散步、用餐並等待夕陽。</p>"},
{id:6,name:"向陽農場",district:"桃園市觀音區",category:"自然農村",tags:["向日葵","採花","親子"],image:"assets/fields/02.jpg?v=20260819-14",stay:"1–2 小時",pace:"田園慢遊",season:"花季最佳",address:"桃園市觀音區藍埔里",hours:"依花季與園區公告",ticket:"依當季活動內容",reminder:"花況受天候影響，行前確認",lead:"大片花田隨季節更換色彩，適合親子散步、拍照，也能認識農場的栽培日常。",body:"<h2>跟著花季安排旅行</h2><p>不同月份的花況與活動內容會調整，建議出發前確認當期主題。園區多為戶外空間，晴天請做好防曬與補水。</p>"},
{id:7,name:"拉拉山水蜜桃",district:"桃園市復興區",category:"山林果香",tags:["水蜜桃","採果","部落"],image:"assets/fields/01.jpg?v=20260819-14",stay:"半日",pace:"產地體驗",season:"夏季",address:"桃園市復興區拉拉山地區",hours:"果園依預約時段開放",ticket:"採果體驗請事先預約",reminder:"果期與採果量依當年氣候",lead:"在高山果園裡認識一顆水蜜桃從開花到採收的旅程，也遇見農家與山林共存的日常。",body:"<h2>山霧孕育的甜味</h2><p>拉拉山的日夜溫差與山區氣候，形成獨特的果實風味。採果體驗通常由果農帶領，除了挑選成熟果實，也會分享栽培與照顧果園的細節。</p>"},
{id:8,name:"大溪老街",district:"桃園市大溪區",category:"老街時光",tags:["巴洛克街屋","木藝","古早味"],image:"assets/fields/02.jpg?v=20260819-14",stay:"2–3 小時",pace:"老城散步",season:"四季皆宜",address:"桃園市大溪區和平路、中山路",hours:"戶外全天，店家各自營業",ticket:"自由參觀",reminder:"假日人潮較多，建議早到",lead:"從牌樓立面、木藝工坊到街角小吃，大溪老街把歷史放進仍在運作的生活裡。",body:"<h2>看建築，也看生活</h2><p>街屋立面融合巴洛克裝飾與傳統圖案，形成大溪辨識度極高的城市表情。散步時不妨抬頭觀察山牆，再走進巷弄尋找木藝、糕餅與豆干等地方產業。</p><h2>順遊提案</h2><p>可從和平路出發，串連中山路、中正公園與木藝館舍；若時間充裕，再走至河岸欣賞大漢溪景色。</p>"},
{id:9,name:"石門水庫",district:"桃園市大溪區／龍潭區",category:"湖光水色",tags:["水庫","湖景","生態"],image:"assets/fields/03.jpg?v=20260819-14",stay:"2–4 小時",pace:"湖畔慢遊",season:"春秋最佳",address:"桃園市大溪區復興里",hours:"園區開放依管理單位公告",ticket:"部分區域或停車依規定收費",reminder:"範圍廣，建議預先安排移動方式",lead:"遼闊湖面、山林與水利工程交織，是能同時閱讀自然與城市用水故事的場域。",body:"<h2>湖光與工程並置</h2><p>從不同觀景點能看見壩體、溢洪道與山谷水面。季節、水位與光線都會改變風景，適合放慢腳步停留。</p>"},
{id:10,name:"小烏來天空步道",district:"桃園市復興區",category:"峽谷秘境",tags:["天空步道","瀑布","峽谷"],image:"assets/fields/04.jpg?v=20260819-14",stay:"2–3 小時",pace:"山谷探索",season:"四季皆宜",address:"桃園市復興區義盛里",hours:"開放時間依園區公告",ticket:"入場與預約依最新公告",reminder:"雨後路面濕滑，請注意腳步",lead:"透明觀景平台向溪谷伸展，以不同高度欣賞瀑布、岩壁與山林層次。",body:"<h2>從高處讀一座峽谷</h2><p>天空步道讓視線越過樹梢直抵溪谷，周邊步道還可串連瀑布與山林景觀。建議預留充裕時間，依體力選擇適合路線。</p>"}
];
document.addEventListener("DOMContentLoaded",()=>{const id=Number(new URLSearchParams(location.search).get("id"))||1;const item=fieldItems.find(f=>f.id===id)||fieldItems[0];document.title=item.name+"｜桃園偏鄉輕旅行";document.querySelector('meta[name="description"]').content=item.lead;document.getElementById("fieldTitle").textContent=item.name;document.getElementById("crumbTitle").textContent=item.name;document.getElementById("fieldDistrict").textContent=item.district;document.getElementById("fieldCategory").textContent=item.category;document.getElementById("fieldStay").textContent=item.stay;document.getElementById("fieldPace").textContent=item.pace;document.getElementById("fieldSeason").textContent=item.season;document.getElementById("fieldAddress").textContent=item.address;document.getElementById("fieldHours").textContent=item.hours;document.getElementById("fieldTicket").textContent=item.ticket;document.getElementById("fieldReminder").textContent=item.reminder;document.getElementById("mapTitle").textContent=item.name;document.getElementById("tagRow").innerHTML=item.tags.map(t=>"<span># "+t+"</span>").join("");const image=document.getElementById("fieldImage");image.src=item.image;image.alt=item.name+"場域景觀";document.getElementById("fieldContent").innerHTML="<p class='lead'>"+item.lead+"</p>"+item.body+"<a class='back-link' href='場域介紹.html'><i class='fa-solid fa-arrow-left'></i> 返回場域介紹</a>";const related=fieldItems.filter(f=>f.id!==item.id).slice(0,3);document.getElementById("relatedGrid").innerHTML=related.map(f=>"<a class='related-card' href='場域詳情.html?id="+f.id+"'><img src='"+f.image+"' alt='' loading='lazy'><div><small>"+f.category+" · "+f.district+"</small><h3>"+f.name+"</h3></div></a>").join("")});