const newsItems=[
{id:1,category:"活動快訊",date:"2026-08-19",title:"秋季拉拉山採果體驗，早鳥報名正式開跑！",image:"https://images.unsplash.com/photo-1542223189-67a03fa0f0bd?q=80&w=1600&auto=format&fit=crop",lead:"跟著果農走進山霧繚繞的果園，在最舒服的季節親手採下當季果實，認識高山農業與產地日常。",body:"<h2>秋日限定的山林果香</h2><p>今年的採果體驗將從九月起分梯開放，內容包含產地導覽、採果教學與農村午茶。旅人可在果農帶領下辨識果實成熟度，也能了解友善耕作如何與山林環境共存。</p><h2>報名資訊</h2><ul><li>活動地點：桃園市復興區拉拉山地區</li><li>活動梯次：每週六、日，上午與下午各一梯</li><li>適合對象：一般旅客與親子家庭</li></ul><div class='article-note'>山區天候變化快，建議攜帶薄外套、防滑鞋與個人飲水；實際採果內容依當週果況彈性調整。</div><p>完成報名後，系統將寄送集合地點與行前提醒。名額採小團制，額滿即停止受理。</p>"},
{id:2,category:"系統公告",date:"2026-08-15",title:"數位集章趣功能更新維護通知",image:"https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=1600&auto=format&fit=crop",lead:"為提升定位速度與集章穩定度，數位集章服務將進行短暫維護。",body:"<h2>維護時間與影響範圍</h2><p>維護期間將暫停定位集章、任務進度同步與獎勵兌換，其他旅遊資訊與購物功能不受影響。</p><ul><li>維護時間：8 月 21 日 00:30 至 04:30</li><li>影響功能：定位打卡、數位集章、獎勵兌換</li></ul><div class='article-note'>已完成但尚未同步的集章紀錄會保留於裝置中，服務恢復後請重新開啟頁面完成同步。</div>"},
{id:3,category:"好康優惠",date:"2026-08-10",title:"大溪老街聯名套票發售，限量贈送特色木藝紀念品",image:"https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1600&auto=format&fit=crop",lead:"用一張套票串起老街走讀、地方滋味與木藝體驗，慢慢認識大溪的生活紋理。",body:"<h2>套票內容</h2><p>聯名套票整合指定店家消費券、木藝館舍導覽與體驗折抵，適合安排半日到一日散步行程。</p><ul><li>老街指定店家折抵券</li><li>木藝手作體驗優惠</li><li>限量木藝紀念品一份</li></ul><p>贈品數量有限，請於購票後依電子票券指示至服務點兌換。</p>"},
{id:4,category:"活動快訊",date:"2026-08-05",title:"觀音蓮花季一日遊開放報名，體驗乘坐大王蓮",image:"https://images.unsplash.com/photo-1506012787146-f92b2d7d6d96?q=80&w=1600&auto=format&fit=crop",lead:"晨光裡賞花、走訪農村，再以地方風味餐收尾，安排一趟輕鬆的夏日小旅行。",body:"<h2>一日遊亮點</h2><p>行程以蓮田導覽為主軸，串連農村散步、季節體驗與在地飲食。大王蓮乘坐將依現場植株與天候狀況開放。</p><ul><li>專人蓮田生態解說</li><li>地方風味午餐</li><li>農村小旅行與季節手作</li></ul>"},
{id:5,category:"好康優惠",date:"2026-08-01",title:"歡慶旅遊網會員突破十萬！紅利點數雙倍送活動",image:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1600&auto=format&fit=crop",lead:"謝謝每一位旅人陪伴在地旅行成長，會員期間限定享點數雙倍回饋。",body:"<h2>活動辦法</h2><p>活動期間以會員身分完成指定體驗預訂或在地好物訂單，符合資格的消費將於訂單完成後獲得雙倍點數。</p><div class='article-note'>取消、退款或未完成的訂單不列入回饋；點數入帳與使用期限以會員中心顯示為準。</div>"},
{id:6,category:"系統公告",date:"2026-07-28",title:"AI 智慧推薦系統 Beta 版上線邀請測試",image:"https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600&auto=format&fit=crop",lead:"輸入旅行時間、同行成員與偏好，讓系統整理出適合你的桃園偏鄉路線。",body:"<h2>Beta 版可以做什麼</h2><p>系統會依旅遊天數、交通方式與主題偏好，組合場域、體驗與在地好物，並提供可調整的行程順序。</p><p>測試期間歡迎透過頁面回饋入口告訴我們建議，協助後續優化推薦準確度與操作流程。</p>"},
{id:7,category:"活動快訊",date:"2026-07-20",title:"龍潭三坑老街：客庄文化深度導覽免費體驗",image:"https://images.unsplash.com/photo-1596748434676-e91b5c404cfd?q=80&w=1600&auto=format&fit=crop",lead:"跟著在地導覽員穿過老街、古厝與水圳，在故事裡感受客庄的日常。",body:"<h2>走讀路線</h2><p>本次導覽從三坑老街出發，沿途介紹聚落發展、信仰與生活產業，再步行至自然生態公園認識水圳地景。</p><ul><li>全程約 2 小時</li><li>每梯限額 20 名</li><li>建議穿著好走的鞋並自備飲水</li></ul>"},
{id:8,category:"好康優惠",date:"2026-07-12",title:"新屋綠色隧道自行車租借優惠，平日享第二台半價",image:"https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=1600&auto=format&fit=crop",lead:"沿著防風林與海岸騎行，平日結伴出發可享指定車款第二台半價。",body:"<h2>優惠使用方式</h2><p>於活動頁領取電子憑證後，至指定合作店家出示會員條碼即可使用。優惠以同筆租借、同車種較低價者計算。</p><div class='article-note'>連續假期與國定假日不適用；安全帽與基本車況檢查均由租借店家提供。</div>"}
];
document.addEventListener("DOMContentLoaded",()=>{const id=Number(new URLSearchParams(location.search).get("id"))||1;const item=newsItems.find(n=>n.id===id)||newsItems[0];document.title=item.title+"｜桃園偏鄉輕旅行";document.querySelector('meta[name="description"]').content=item.lead;document.getElementById("newsCategory").textContent=item.category;document.getElementById("sideCategory").textContent=item.category;document.getElementById("newsTitle").textContent=item.title;document.getElementById("crumbTitle").textContent=item.title;document.getElementById("newsDate").textContent=item.date.replaceAll("-",".");document.getElementById("sideDate").textContent=item.date.replaceAll("-",".");const image=document.getElementById("newsImage");image.src=item.image;image.alt=item.title;document.getElementById("newsContent").innerHTML="<p class='lead'>"+item.lead+"</p>"+item.body+"<a class='back-link' href='最新消息.html'><i class='fa-solid fa-arrow-left'></i> 返回最新消息</a>";const related=newsItems.filter(n=>n.id!==item.id).slice(0,3);document.getElementById("relatedGrid").innerHTML=related.map(n=>"<a class='related-card' href='最新消息詳情.html?id="+n.id+"'><img src='"+n.image+"' alt='' loading='lazy'><div><small>"+n.category+" · "+n.date+"</small><h3>"+n.title+"</h3></div></a>").join("")});